### ISSUE TITLE
lazy conf generates error and escapes script.

### ISSUE THREAD

**Issue by kanbie** [Imagix/uvtt2fgu#25]
Love the script Imagix, use this for tons of my Sunday games.

I was working with getting a JPG/XML export setup in the .conf file set in &Appdata& and the script generated a 0kb jpg with no xml.

With the conf file:
```
[default]
xmlpath=!PATH!\ExportedMaps
writepng=False
jpgpath=!PATH!\ExportedMaps

#jpgQuality=75
#jpgSubsampling=2
#jpgOptimize=True

force=True
``
--CMD--
PS !PATH!> ./uvtt2fgu.exe ./SuperCave.dd2vtt
Traceback (most recent call last):
  File "uvtt2fgu.py", line 617, in <module>
  File "uvtt2fgu.py", line 611, in main
  File "uvtt2fgu.py", line 451, in processFile
  File "uvtt2fgu.py", line 418, in writeJpg
  File "PIL\Image.py", line 2172, in save
  File "PIL\JpegImagePlugin.py", line 655, in _save
ValueError: Invalid quality setting
[23088] Failed to execute script uvtt2fgu
----
```
The error is generated and just the 0kb jpg exists.
The error can be avoided by removing the comments in the above. However I wouldn't expect that I have to set those flags as those are the default values that are used without a config.

**Comment by Imagix** [comment]
Thank-you for your report.  I've published a new v1.5.1 that should fix this issue.
